[package]
name = "racer"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "=0.4.13"
racer_logic = { path = "../racer_logic" }
#racer_onnx_controller = { path = "../racer_onnx_controller" }

[package.metadata.android]
package_name = "com.stepanmracek.racer"
assets = "../assets/"
build_targets = ["aarch64-linux-android"]

[package.metadata.android.activity_attributes]
"android:exported" = "true"
"android:screenOrientation" = "userPortrait"
