[package]
name = "racer_headless"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
kdam = "0.6.3"
racer_logic = { path = "../racer_logic" }
racer_onnx_controller = { path = "../racer_onnx_controller" }
racer_ndarray_controller = { path = "../racer_ndarray_controller" }
