[package]
name = "train_ndarray_controller"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = { version = "0.17.1", features = ["serde"] }
ndarray-rand = "0.16.0"
racer_logic = { path = "../racer_logic" }
ga = { path = "../ga" }
racer_ndarray_controller = { path = "../controllers/ndarray" }
